# Generated by Django 4.2.7 on 2023-11-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_sides'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
